title: "PSYAARA"
description: "Personal portfolio, projects, and notes"
theme: jekyll-theme-cayman   # Keeps your selected Jekyll theme active
show_downloads: false        # Set to false to remove default zip/tar download buttons
